### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Devraj004** [CiscoBlockChain/YOLO-Pi#4]
Hi,
I tried to run the code with out docker file and getting "Segmentation fault" error. Is the use of docker mandatory here ? if not , need your help to resolve the error.

Many thanks.

(cv3) pi@raspberrypi:~/YOLO-Pi-master/src $ python yolo-pi.py
Using TensorFlow backend.
Segmentation fault

**Comment by vallard** [comment]
If you look at the Dockerfile.x86 you will see the library versions we use. We are trying to get this all up in the next two weeks.  Sorry for delays.  Using updated versions of opencv gave us errors.

**Comment by vallard** [comment]
Ok, we've updated.  If you are getting a segmentation fault check the prereqs.  Take a look at the Raspberry Pi docker file.  That has all the packages and versions that we are using.  We seem to be working ok with the new code but its pretty specific in that it tries to send the output of YOLO to MQTT for use in our blockchain project.  I'm gonna close this issue but open if you need some more help.
